spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_MYSQL_URL}
    username: ${LOCAL_MYSQL_USER}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

cors:
  allowed-origins:
    - ${FRONT_ORIGIN}

logging:
  level:
    root: info